#ifndef GADGET_INPUT_ENUMS_H
#define GADGET_INPUT_ENUMS_H

namespace Gadget{
	//We can safely remove/ignore a lot of these (mostly the system keys) but for now we're just gonna list everything
	enum class ButtonID{
		None = 0,
		//Standard Gamepad Layout Buttons
		Gamepad_Shoulder_Left1,
		Gamepad_Shoulder_Left2,
		Gamepad_Shoulder_Right1,
		Gamepad_Shoulder_Right2,
		Gamepad_DPad_Up,
		Gamepad_DPad_Down,
		Gamepad_DPad_Left,
		Gamepad_DPad_Right,
		Gamepad_Start,
		Gamepad_Select,
		Gamepad_Home,
		Gamepad_Face_Up,
		Gamepad_Face_Down,
		Gamepad_Face_Left,
		Gamepad_Face_Right,
		Gamepad_AnalogClick_Left,
		Gamepad_AnalogClick_Right,

		//Mouse
		Mouse_LeftMouseButton,
		Mouse_RightMouseButton,
		Mouse_MiddleMouseButton,
		Mouse_Button4,
		Mouse_Button5, //Some mice have more than 5 buttons but Windows doesn't natively support this

		//Keyboard
		Keyboard_0,
		Keyboard_1,
		Keyboard_2,
		Keyboard_3,
		Keyboard_4,
		Keyboard_5,
		Keyboard_6,
		Keyboard_7,
		Keyboard_8,
		Keyboard_9,

		Keyboard_A,
		Keyboard_B,
		Keyboard_C,
		Keyboard_D,
		Keyboard_E,
		Keyboard_F,
		Keyboard_G,
		Keyboard_H,
		Keyboard_I,
		Keyboard_J,
		Keyboard_K,
		Keyboard_L,
		Keyboard_M,
		Keyboard_N,
		Keyboard_O,
		Keyboard_P,
		Keyboard_Q,
		Keyboard_R,
		Keyboard_S,
		Keyboard_T,
		Keyboard_U,
		Keyboard_V,
		Keyboard_W,
		Keyboard_X,
		Keyboard_Y,
		Keyboard_Z,

		Keyboard_Quote,
		Keyboard_Backslash,
		Keyboard_Comma,
		Keyboard_CurrencyUnit,
		Keyboard_CurrencySubUnit,
		Keyboard_DecimalSeparator,
		Keyboard_Equals,
		Keyboard_BackQuote,
		Keyboard_LeftBracket,
		Keyboard_Minus,
		Keyboard_Period,
		Keyboard_RightBracket,
		Keyboard_SemiColon,
		Keyboard_Slash,
		Keyboard_Space,
		Keyboard_Tab,
		Keyboard_ThousandsSeparator,
		//The following special characters don't have corresponding physical keys
		Keyboard_Ampersand,
		Keyboard_Asterisk,
		Keyboard_AT,
		Keyboard_Caret,
		Keyboard_Colon,
		Keyboard_Dollar,
		Keyboard_Exclaim,
		Keyboard_GreaterThan,
		Keyboard_Hash,
		Keyboard_LeftParenthesis,
		Keyboard_LessThan,
		Keyboard_Percent,
		Keyboard_Plus,
		Keyboard_Question,
		Keyboard_QuoteDouble,
		Keyboard_RightParenthesis,
		Keyboard_Underscore,

		Keyboard_Arrow_Up,
		Keyboard_Arrow_Down,
		Keyboard_Arrow_Left,
		Keyboard_Arrow_Right,

		Keyboard_ApplicationControl_Back, //No idea what these are
		Keyboard_ApplicationControl_Bookmarks,
		Keyboard_ApplicationControl_Forward,
		Keyboard_ApplicationControl_Home,
		Keyboard_ApplicationControl_Refresh,
		Keyboard_ApplicationControl_Search,
		Keyboard_ApplicationControl_Stop,

		Keyboard_Application,
		Keyboard_App1, //???
		Keyboard_App2, //???
		Keyboard_Again,
		Keyboard_AltErase,
		Keyboard_Audio_Mute,
		Keyboard_Audio_Previous,
		Keyboard_Audio_Next,
		Keyboard_Audio_Play,
		Keyboard_Audio_Stop,
		Keyboard_Audio_Rewind,
		Keyboard_Audio_FastForward,
		Keyboard_Backspace,
		Keyboard_Brightness_Down,
		Keyboard_Brightness_Up,
		Keyboard_Calculator,
		Keyboard_Cancel,
		Keyboard_CapsLock,
		Keyboard_Clear,
		Keyboard_ClearAgain,
		Keyboard_Computer,
		Keyboard_Copy,
		Keyboard_CrSel, //???
		Keyboard_Cut,
		Keyboard_Delete,
		Keyboard_DisplaySwitch,
		Keyboard_Eject,
		Keyboard_End,
		Keyboard_Escape,
		Keyboard_Execute,
		Keyboard_ExSel, //???
		Keyboard_F1,
		Keyboard_F2,
		Keyboard_F3,
		Keyboard_F4,
		Keyboard_F5,
		Keyboard_F6,
		Keyboard_F7,
		Keyboard_F8,
		Keyboard_F9,
		Keyboard_F10,
		Keyboard_F11,
		Keyboard_F12,
		Keyboard_F13,
		Keyboard_F14,
		Keyboard_F15,
		Keyboard_F16,
		Keyboard_F17,
		Keyboard_F18,
		Keyboard_F19,
		Keyboard_F20,
		Keyboard_F21,
		Keyboard_F22,
		Keyboard_F23,
		Keyboard_F24,
		Keyboard_Find,
		Keyboard_Help,
		Keyboard_Home,
		Keyboard_Insert,
		Keyboard_Illumination_Down,
		Keyboard_Illumination_Up,
		Keyboard_Illumination_Toggle,
		Keyboard_LeftAlt,
		Keyboard_LeftCtrl,
		Keyboard_LeftGUI,
		Keyboard_LeftShift,
		Keyboard_Mail,
		Keyboard_MediaSelect,
		Keyboard_Menu,
		Keyboard_ModeSwitch,
		Keyboard_Mute,
		Keyboard_NumLock,
		Keyboard_Oper, //???
		Keyboard_Out,
		Keyboard_PageDown,
		Keyboard_PageUp,
		Keyboard_Paste,
		Keyboard_Pause,
		Keyboard_Power,
		Keyboard_PrintScreen,
		Keyboard_Prior,
		Keyboard_RightAlt,
		Keyboard_RightCtrl,
		Keyboard_Return, //AKA Enter
		Keyboard_Return2,
		Keyboard_RightGUI,
		Keyboard_RightShift,
		Keyboard_ScrollLock,
		Keyboard_Select,
		Keyboard_Separator,
		Keyboard_Sleep,
		Keyboard_Stop,
		Keyboard_SysReq,
		Keyboard_Undo,
		Keyboard_VolumeDown,
		Keyboard_VolumeUp,
		Keyboard_WWW,
		Keyboard_SoftLeft,
		Keyboard_SoftRight,
		Keyboard_Call,
		Keyboard_EndCall,

		Keyboard_Keypad_0,
		Keyboard_Keypad_00,
		Keyboard_Keypad_000,
		Keyboard_Keypad_1,
		Keyboard_Keypad_2,
		Keyboard_Keypad_3,
		Keyboard_Keypad_4,
		Keyboard_Keypad_5,
		Keyboard_Keypad_6,
		Keyboard_Keypad_7,
		Keyboard_Keypad_8,
		Keyboard_Keypad_9,

		Keyboard_Keypad_A,
		Keyboard_Keypad_B,
		Keyboard_Keypad_C,
		Keyboard_Keypad_D,
		Keyboard_Keypad_E,
		Keyboard_Keypad_F,

		Keyboard_Keypad_Ampersand,
		Keyboard_Keypad_AT,
		Keyboard_Keypad_Colon,
		Keyboard_Keypad_Comma,
		Keyboard_Keypad_DoubleAmpersand,
		Keyboard_Keypad_DoubleVerticalBar,
		Keyboard_Keypad_Decimal,
		Keyboard_Keypad_Divide,
		Keyboard_Keypad_Equal,
		Keyboard_Keypad_Equal_AS400, //???
		Keyboard_Keypad_Exclamation,
		Keyboard_Keypad_GreaterThan,
		Keyboard_Keypad_Hash,
		Keyboard_Keypad_Hexadecimal, //???
		Keyboard_Keypad_LeftBrace,
		Keyboard_Keypad_LeftParenthesis,
		Keyboard_Keypad_LessThan,
		Keyboard_Keypad_Minus,
		Keyboard_Keypad_Multiply,
		Keyboard_Keypad_Octal,
		Keyboard_Keypad_Percent,
		Keyboard_Keypad_Period,
		Keyboard_Keypad_Plus,
		Keyboard_Keypad_PlusMinus,
		Keyboard_Keypad_Power,
		Keyboard_Keypad_RightBrace,
		Keyboard_Keypad_RightParenthesis,
		Keyboard_Keypad_Space,
		Keyboard_Keypad_Tab,
		Keyboard_Keypad_VerticalBar,
		Keyboard_Keypad_XOR,

		Keyboard_Keypad_Backspace,
		Keyboard_Keypad_Binary,
		Keyboard_Keypad_Clear,
		Keyboard_Keypad_ClearEntry,
		Keyboard_Keypad_Enter,
		Keyboard_Keypad_MemAdd,
		Keyboard_Keypad_MemClear,
		Keyboard_Keypad_MemDivide,
		Keyboard_Keypad_MemMultiply,
		Keyboard_Keypad_MemRecall,
		Keyboard_Keypad_MemStore,
		Keyboard_Keypad_MemSubtract,

		Keyboard_Unknown
	};

	enum class AxisID{
		None = 0,
		//Standard Gamepad Layout
		Gamepad_LeftStick_Horizontal,
		Gamepad_LeftStick_Vertical,
		Gamepad_RightStick_Horizontal,
		Gamepad_RightStick_Vertical,
		Gamepad_LeftTrigger,
		Gamepad_RightTrigger,

		//Mouse
		Mouse_Move_Horizontal,
		Mouse_Move_Vertical,
		Mouse_Scroll_Horizontal,
		Mouse_Scroll_Vertical,
	};
}

#endif //!GADGET_INPUT_ENUMS_H