name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          submodules: recursive
          
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
          
    - name: Build Solution (Debug)
      run: MSBuild.exe -restore GadgetEngine.sln /property:Configuration=Debug

    - name: Build Solution (Develop)
      run: MSBuild.exe -restore GadgetEngine.sln /property:Configuration=Develop

    - name: Build Solution (Release)
      run: MSBuild.exe -restore GadgetEngine.sln /property:Configuration=Release
      
    - name: Run Tests (Debug)
      run: .\Build\Tests\Debug\Tests.exe
      
    - name: Run Tests (Develop)
      run: .\Build\Tests\Develop\Tests.exe
      
    - name: Run Tests (Release)
      run: .\Build\Tests\Release\Tests.exe
